{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aapt2-proto",
    "version": "8.1.0-10154469",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aapt2-proto-8.1.0-10154469.jar",
          "url": "aapt2-proto-8.1.0-10154469.jar",
          "size": 762370,
          "sha512": "e0d13cca1b8b4c7a28094f46f0673c4ade4e0780fc52a5a8d8c6dc10b37aeae6c67e136bd79823aa5865251f04915b2c879670a48ac068c5442d479f88a34b28",
          "sha256": "6d8d14b91285cc7c1b73460f413bb3f80672dc34dc506ed578fba1f6dde8661e",
          "sha1": "49bcae5918bf1f4a4177b33d44473055d9e5fe1c",
          "md5": "509b6b3fcc7fa0e6c4ff1380c6b8edcc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.19.3"
          }
        }
      ],
      "files": [
        {
          "name": "aapt2-proto-8.1.0-10154469.jar",
          "url": "aapt2-proto-8.1.0-10154469.jar",
          "size": 762370,
          "sha512": "e0d13cca1b8b4c7a28094f46f0673c4ade4e0780fc52a5a8d8c6dc10b37aeae6c67e136bd79823aa5865251f04915b2c879670a48ac068c5442d479f88a34b28",
          "sha256": "6d8d14b91285cc7c1b73460f413bb3f80672dc34dc506ed578fba1f6dde8661e",
          "sha1": "49bcae5918bf1f4a4177b33d44473055d9e5fe1c",
          "md5": "509b6b3fcc7fa0e6c4ff1380c6b8edcc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aapt2-proto-8.1.0-10154469-javadoc.jar",
          "url": "aapt2-proto-8.1.0-10154469-javadoc.jar",
          "size": 1090967,
          "sha512": "382b112d795e1bcf7131225d42ad5d6af156b0dae9e6ff45a64379eba14224ed96ed52e3dcfacab09599ba3bc0a50436e795ffeb800e638cbb016fd7c4843bd8",
          "sha256": "ec98a934a8cd1de0b97f44e18fde2b3b06ffd6ed75e3acc8415e90794dc981fa",
          "sha1": "9124f98060d9af1b665a706e1a95f667f7fca8e5",
          "md5": "d099efc727aa0cc6019f4f30efc05b3c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aapt2-proto-8.1.0-10154469-sources.jar",
          "url": "aapt2-proto-8.1.0-10154469-sources.jar",
          "size": 208203,
          "sha512": "e2c56f3e71fe9afc687704d0c9974c5d5b9c255513fde01a872ec9dccf567bb63f9b11cdd130ac24ec4547fc2559cfcc2253f5bd6724265a33e719de60f865f1",
          "sha256": "4a6230c2fa3dd285e295fe60d19e2f23eb2b4b752e0c5e4088ca6c118b5c27d7",
          "sha1": "ed41efad84ba5c75d4e10a9859e22355923fc899",
          "md5": "b41f2226466b1d8a1f0c472bdfc8c351"
        }
      ]
    }
  ]
}
