{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.1.0.jar",
          "url": "builder-8.1.0.jar",
          "size": 11852762,
          "sha512": "180857b2c09738c7181d4f6868de519761d72a40dd9719ffc82a5c5ff4e6cc623bd27b7791497af25ed091a41a88c3c009835c5eacd0ce8d06fe8b83508429cc",
          "sha256": "be41a2a8b1056729c3d4bf4c79cc9c0f344c77932bfdb31961d96ce70bd187da",
          "sha1": "0602b620b1ee65828181b543bc1790efdfde39cf",
          "md5": "eabdb2a9a938c21fe48a9d5a28c09e99"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20-RC2"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.67"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.67"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.1.0.jar",
          "url": "builder-8.1.0.jar",
          "size": 11852762,
          "sha512": "180857b2c09738c7181d4f6868de519761d72a40dd9719ffc82a5c5ff4e6cc623bd27b7791497af25ed091a41a88c3c009835c5eacd0ce8d06fe8b83508429cc",
          "sha256": "be41a2a8b1056729c3d4bf4c79cc9c0f344c77932bfdb31961d96ce70bd187da",
          "sha1": "0602b620b1ee65828181b543bc1790efdfde39cf",
          "md5": "eabdb2a9a938c21fe48a9d5a28c09e99"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.1.0-javadoc.jar",
          "url": "builder-8.1.0-javadoc.jar",
          "size": 400630,
          "sha512": "3fb6911c1235694bfbe5542a8b13a4b9f9add6f837da82b73e144f703d925a99e4536d64c21c4ae467e4dc2e624330fe0c4b1b011ab152108909ae6618debd74",
          "sha256": "e4e2659c0850c889d35236b408b7c36ea06467ea2a1f512db96651355e3bae4d",
          "sha1": "8b57d0c3b6419fc39b0ca541d4ebb86eb088e171",
          "md5": "802f9e2c38f996e60e065841d3e1da96"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.1.0-sources.jar",
          "url": "builder-8.1.0-sources.jar",
          "size": 282001,
          "sha512": "f47bd9f3e007c712bb4f77a87817f60c0075b9f3fbf98d25db9478473eda470653d164a4180e21ce47c8f9610f5d262dbe69baa0172f339b49ca26e97ebb6cde",
          "sha256": "f242d380f3d5c79e907c271023cbd5c49d123e433c4178222a566e6374eafbc7",
          "sha1": "9e853d37b33a3d93160b1fc4ee74b6bda9572ead",
          "md5": "4332f1cb3819989fdac5b72756e968d7"
        },
        {
          "name": "builder-8.1.0-sources.jar",
          "url": "builder-8.1.0-sources.jar",
          "size": 282001,
          "sha512": "f47bd9f3e007c712bb4f77a87817f60c0075b9f3fbf98d25db9478473eda470653d164a4180e21ce47c8f9610f5d262dbe69baa0172f339b49ca26e97ebb6cde",
          "sha256": "f242d380f3d5c79e907c271023cbd5c49d123e433c4178222a566e6374eafbc7",
          "sha1": "9e853d37b33a3d93160b1fc4ee74b6bda9572ead",
          "md5": "4332f1cb3819989fdac5b72756e968d7"
        }
      ]
    }
  ]
}
