{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle",
    "version": "8.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "8.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-8.1.0.jar",
          "url": "gradle-8.1.0.jar",
          "size": 10817071,
          "sha512": "03698392307064ffa6d1c751c8160a474bb3b752ad80e8303937074368aef1c80d5b26a5a01b5ea7a34c85a085e4ed3184dbdaadda7752b610957b37cf9b3a77",
          "sha256": "bee5ca8b8255096decc397372c104e4a2a2d7c690d712e10181609ed85cd1cb2",
          "sha1": "fcd4612dc9b74db28fdb6a4b6a6ddc6008970428",
          "md5": "8b4eed25442eb2dd08559f23ab916297"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-settings-api",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "repository",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "8.1.0-10154469"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "aaptcompiler",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "crash",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "shared",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint-model",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint-typedef-remover",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-compiler-common",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "baseLibrary",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-device-provider-ddmlib-proto",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-device-provider-gradle-proto",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-additional-test-output-proto",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-coverage-proto",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-emulator-control-proto",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-logcat-proto",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-apk-installer-proto",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-retention-proto",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-result-listener-gradle-proto",
          "version": {
            "requires": "31.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20-RC2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "transform-api",
          "version": {
            "requires": "2.0.0-deprecated-use-gradle-api"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.67"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "bundletool",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.android.tools.build.jetifier",
          "module": "jetifier-core",
          "version": {
            "requires": "1.0.0-beta10"
          }
        },
        {
          "group": "com.android.tools.build.jetifier",
          "module": "jetifier-processor",
          "version": {
            "requires": "1.0.0-beta10"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.19.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.19.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-core",
          "version": {
            "requires": "1.45.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty",
          "version": {
            "requires": "1.45.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.45.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.45.1"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "core-proto",
          "version": {
            "requires": "0.0.8-alpha08"
          }
        },
        {
          "group": "com.google.flatbuffers",
          "module": "flatbuffers-java",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.tensorflow",
          "module": "tensorflow-lite-metadata",
          "version": {
            "requires": "0.1.0-rc2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "8.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-8.1.0.jar",
          "url": "gradle-8.1.0.jar",
          "size": 10817071,
          "sha512": "03698392307064ffa6d1c751c8160a474bb3b752ad80e8303937074368aef1c80d5b26a5a01b5ea7a34c85a085e4ed3184dbdaadda7752b610957b37cf9b3a77",
          "sha256": "bee5ca8b8255096decc397372c104e4a2a2d7c690d712e10181609ed85cd1cb2",
          "sha1": "fcd4612dc9b74db28fdb6a4b6a6ddc6008970428",
          "md5": "8b4eed25442eb2dd08559f23ab916297"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-8.1.0-javadoc.jar",
          "url": "gradle-8.1.0-javadoc.jar",
          "size": 579405,
          "sha512": "e1a30f7dcb433e491a93cc1b6a077605c2bcf0e00cc13f730545f1bfc7d919dc841b4d5e42c0c6b8deb7636dfea5e39872c1e9081b0366b1b431971a0c53b684",
          "sha256": "c5a2175011f479586e2a4792a0d6aee64119300c772206409233bf79c7dc56cf",
          "sha1": "87d56a4b8ad665ce475d038c0edf0a9f9459b3fa",
          "md5": "0a3edb6de0586b0b0686988b0e5f84cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-8.1.0-sources.jar",
          "url": "gradle-8.1.0-sources.jar",
          "size": 2875923,
          "sha512": "a6c15242325fddf08fdd8dce0f900dda26c93e93082e93fb281ca27174feb8d13e29ff4f51915ef6abf559b9c7b1a02a4459cbe455c4a6d7a1d2d4254ca3a3e8",
          "sha256": "052cdc75d4ce2497b3905a048a2076415c74387e0ee9ab36076a4471f1732408",
          "sha1": "acd13b390c9425aa3e7a5e2fa822450368a62b93",
          "md5": "83887b333fbe57fd500a0c2759be1af2"
        },
        {
          "name": "gradle-8.1.0-sources.jar",
          "url": "gradle-8.1.0-sources.jar",
          "size": 2875923,
          "sha512": "a6c15242325fddf08fdd8dce0f900dda26c93e93082e93fb281ca27174feb8d13e29ff4f51915ef6abf559b9c7b1a02a4459cbe455c4a6d7a1d2d4254ca3a3e8",
          "sha256": "052cdc75d4ce2497b3905a048a2076415c74387e0ee9ab36076a4471f1732408",
          "sha1": "acd13b390c9425aa3e7a5e2fa822450368a62b93",
          "md5": "83887b333fbe57fd500a0c2759be1af2"
        }
      ]
    }
  ]
}
